// Auto-generated by scripts/generate-icon-lists.ts
// DO NOT EDIT MANUALLY

export interface PrimeIcon {
  name: string
  className: string
}

export const PRIME_ICONS: PrimeIcon[] = [
  {
    name: 'address-book',
    className: 'pi pi-address-book',
  },
  {
    name: 'align-center',
    className: 'pi pi-align-center',
  },
  {
    name: 'align-justify',
    className: 'pi pi-align-justify',
  },
  {
    name: 'align-left',
    className: 'pi pi-align-left',
  },
  {
    name: 'align-right',
    className: 'pi pi-align-right',
  },
  {
    name: 'amazon',
    className: 'pi pi-amazon',
  },
  {
    name: 'android',
    className: 'pi pi-android',
  },
  {
    name: 'angle-double-down',
    className: 'pi pi-angle-double-down',
  },
  {
    name: 'angle-double-left',
    className: 'pi pi-angle-double-left',
  },
  {
    name: 'angle-double-right',
    className: 'pi pi-angle-double-right',
  },
  {
    name: 'angle-double-up',
    className: 'pi pi-angle-double-up',
  },
  {
    name: 'angle-down',
    className: 'pi pi-angle-down',
  },
  {
    name: 'angle-left',
    className: 'pi pi-angle-left',
  },
  {
    name: 'angle-right',
    className: 'pi pi-angle-right',
  },
  {
    name: 'angle-up',
    className: 'pi pi-angle-up',
  },
  {
    name: 'apple',
    className: 'pi pi-apple',
  },
  {
    name: 'arrow-circle-down',
    className: 'pi pi-arrow-circle-down',
  },
  {
    name: 'arrow-circle-left',
    className: 'pi pi-arrow-circle-left',
  },
  {
    name: 'arrow-circle-right',
    className: 'pi pi-arrow-circle-right',
  },
  {
    name: 'arrow-circle-up',
    className: 'pi pi-arrow-circle-up',
  },
  {
    name: 'arrow-down',
    className: 'pi pi-arrow-down',
  },
  {
    name: 'arrow-down-left',
    className: 'pi pi-arrow-down-left',
  },
  {
    name: 'arrow-down-left-and-arrow-up-right-to-center',
    className: 'pi pi-arrow-down-left-and-arrow-up-right-to-center',
  },
  {
    name: 'arrow-down-right',
    className: 'pi pi-arrow-down-right',
  },
  {
    name: 'arrow-left',
    className: 'pi pi-arrow-left',
  },
  {
    name: 'arrow-right',
    className: 'pi pi-arrow-right',
  },
  {
    name: 'arrow-right-arrow-left',
    className: 'pi pi-arrow-right-arrow-left',
  },
  {
    name: 'arrow-up',
    className: 'pi pi-arrow-up',
  },
  {
    name: 'arrow-up-left',
    className: 'pi pi-arrow-up-left',
  },
  {
    name: 'arrow-up-right',
    className: 'pi pi-arrow-up-right',
  },
  {
    name: 'arrow-up-right-and-arrow-down-left-from-center',
    className: 'pi pi-arrow-up-right-and-arrow-down-left-from-center',
  },
  {
    name: 'arrows-alt',
    className: 'pi pi-arrows-alt',
  },
  {
    name: 'arrows-h',
    className: 'pi pi-arrows-h',
  },
  {
    name: 'arrows-v',
    className: 'pi pi-arrows-v',
  },
  {
    name: 'asterisk',
    className: 'pi pi-asterisk',
  },
  {
    name: 'at',
    className: 'pi pi-at',
  },
  {
    name: 'backward',
    className: 'pi pi-backward',
  },
  {
    name: 'ban',
    className: 'pi pi-ban',
  },
  {
    name: 'barcode',
    className: 'pi pi-barcode',
  },
  {
    name: 'bars',
    className: 'pi pi-bars',
  },
  {
    name: 'bell',
    className: 'pi pi-bell',
  },
  {
    name: 'bell-slash',
    className: 'pi pi-bell-slash',
  },
  {
    name: 'bitcoin',
    className: 'pi pi-bitcoin',
  },
  {
    name: 'bolt',
    className: 'pi pi-bolt',
  },
  {
    name: 'book',
    className: 'pi pi-book',
  },
  {
    name: 'bookmark',
    className: 'pi pi-bookmark',
  },
  {
    name: 'bookmark-fill',
    className: 'pi pi-bookmark-fill',
  },
  {
    name: 'box',
    className: 'pi pi-box',
  },
  {
    name: 'briefcase',
    className: 'pi pi-briefcase',
  },
  {
    name: 'building',
    className: 'pi pi-building',
  },
  {
    name: 'building-columns',
    className: 'pi pi-building-columns',
  },
  {
    name: 'bullseye',
    className: 'pi pi-bullseye',
  },
  {
    name: 'calculator',
    className: 'pi pi-calculator',
  },
  {
    name: 'calendar',
    className: 'pi pi-calendar',
  },
  {
    name: 'calendar-clock',
    className: 'pi pi-calendar-clock',
  },
  {
    name: 'calendar-minus',
    className: 'pi pi-calendar-minus',
  },
  {
    name: 'calendar-plus',
    className: 'pi pi-calendar-plus',
  },
  {
    name: 'calendar-times',
    className: 'pi pi-calendar-times',
  },
  {
    name: 'camera',
    className: 'pi pi-camera',
  },
  {
    name: 'car',
    className: 'pi pi-car',
  },
  {
    name: 'caret-down',
    className: 'pi pi-caret-down',
  },
  {
    name: 'caret-left',
    className: 'pi pi-caret-left',
  },
  {
    name: 'caret-right',
    className: 'pi pi-caret-right',
  },
  {
    name: 'caret-up',
    className: 'pi pi-caret-up',
  },
  {
    name: 'cart-arrow-down',
    className: 'pi pi-cart-arrow-down',
  },
  {
    name: 'cart-minus',
    className: 'pi pi-cart-minus',
  },
  {
    name: 'cart-plus',
    className: 'pi pi-cart-plus',
  },
  {
    name: 'chart-bar',
    className: 'pi pi-chart-bar',
  },
  {
    name: 'chart-line',
    className: 'pi pi-chart-line',
  },
  {
    name: 'chart-pie',
    className: 'pi pi-chart-pie',
  },
  {
    name: 'chart-scatter',
    className: 'pi pi-chart-scatter',
  },
  {
    name: 'check',
    className: 'pi pi-check',
  },
  {
    name: 'check-circle',
    className: 'pi pi-check-circle',
  },
  {
    name: 'check-square',
    className: 'pi pi-check-square',
  },
  {
    name: 'chevron-circle-down',
    className: 'pi pi-chevron-circle-down',
  },
  {
    name: 'chevron-circle-left',
    className: 'pi pi-chevron-circle-left',
  },
  {
    name: 'chevron-circle-right',
    className: 'pi pi-chevron-circle-right',
  },
  {
    name: 'chevron-circle-up',
    className: 'pi pi-chevron-circle-up',
  },
  {
    name: 'chevron-down',
    className: 'pi pi-chevron-down',
  },
  {
    name: 'chevron-left',
    className: 'pi pi-chevron-left',
  },
  {
    name: 'chevron-right',
    className: 'pi pi-chevron-right',
  },
  {
    name: 'chevron-up',
    className: 'pi pi-chevron-up',
  },
  {
    name: 'circle',
    className: 'pi pi-circle',
  },
  {
    name: 'circle-fill',
    className: 'pi pi-circle-fill',
  },
  {
    name: 'circle-off',
    className: 'pi pi-circle-off',
  },
  {
    name: 'circle-on',
    className: 'pi pi-circle-on',
  },
  {
    name: 'clipboard',
    className: 'pi pi-clipboard',
  },
  {
    name: 'clock',
    className: 'pi pi-clock',
  },
  {
    name: 'clone',
    className: 'pi pi-clone',
  },
  {
    name: 'cloud',
    className: 'pi pi-cloud',
  },
  {
    name: 'cloud-download',
    className: 'pi pi-cloud-download',
  },
  {
    name: 'cloud-upload',
    className: 'pi pi-cloud-upload',
  },
  {
    name: 'code',
    className: 'pi pi-code',
  },
  {
    name: 'cog',
    className: 'pi pi-cog',
  },
  {
    name: 'comment',
    className: 'pi pi-comment',
  },
  {
    name: 'comments',
    className: 'pi pi-comments',
  },
  {
    name: 'compass',
    className: 'pi pi-compass',
  },
  {
    name: 'copy',
    className: 'pi pi-copy',
  },
  {
    name: 'credit-card',
    className: 'pi pi-credit-card',
  },
  {
    name: 'crown',
    className: 'pi pi-crown',
  },
  {
    name: 'database',
    className: 'pi pi-database',
  },
  {
    name: 'delete-left',
    className: 'pi pi-delete-left',
  },
  {
    name: 'desktop',
    className: 'pi pi-desktop',
  },
  {
    name: 'directions',
    className: 'pi pi-directions',
  },
  {
    name: 'directions-alt',
    className: 'pi pi-directions-alt',
  },
  {
    name: 'discord',
    className: 'pi pi-discord',
  },
  {
    name: 'dollar',
    className: 'pi pi-dollar',
  },
  {
    name: 'download',
    className: 'pi pi-download',
  },
  {
    name: 'eject',
    className: 'pi pi-eject',
  },
  {
    name: 'ellipsis-h',
    className: 'pi pi-ellipsis-h',
  },
  {
    name: 'ellipsis-v',
    className: 'pi pi-ellipsis-v',
  },
  {
    name: 'envelope',
    className: 'pi pi-envelope',
  },
  {
    name: 'equals',
    className: 'pi pi-equals',
  },
  {
    name: 'eraser',
    className: 'pi pi-eraser',
  },
  {
    name: 'ethereum',
    className: 'pi pi-ethereum',
  },
  {
    name: 'euro',
    className: 'pi pi-euro',
  },
  {
    name: 'exclamation-circle',
    className: 'pi pi-exclamation-circle',
  },
  {
    name: 'exclamation-triangle',
    className: 'pi pi-exclamation-triangle',
  },
  {
    name: 'expand',
    className: 'pi pi-expand',
  },
  {
    name: 'external-link',
    className: 'pi pi-external-link',
  },
  {
    name: 'eye',
    className: 'pi pi-eye',
  },
  {
    name: 'eye-slash',
    className: 'pi pi-eye-slash',
  },
  {
    name: 'face-smile',
    className: 'pi pi-face-smile',
  },
  {
    name: 'facebook',
    className: 'pi pi-facebook',
  },
  {
    name: 'fast-backward',
    className: 'pi pi-fast-backward',
  },
  {
    name: 'fast-forward',
    className: 'pi pi-fast-forward',
  },
  {
    name: 'file',
    className: 'pi pi-file',
  },
  {
    name: 'file-arrow-up',
    className: 'pi pi-file-arrow-up',
  },
  {
    name: 'file-check',
    className: 'pi pi-file-check',
  },
  {
    name: 'file-edit',
    className: 'pi pi-file-edit',
  },
  {
    name: 'file-excel',
    className: 'pi pi-file-excel',
  },
  {
    name: 'file-export',
    className: 'pi pi-file-export',
  },
  {
    name: 'file-import',
    className: 'pi pi-file-import',
  },
  {
    name: 'file-o',
    className: 'pi pi-file-o',
  },
  {
    name: 'file-pdf',
    className: 'pi pi-file-pdf',
  },
  {
    name: 'file-plus',
    className: 'pi pi-file-plus',
  },
  {
    name: 'file-word',
    className: 'pi pi-file-word',
  },
  {
    name: 'filter',
    className: 'pi pi-filter',
  },
  {
    name: 'filter-fill',
    className: 'pi pi-filter-fill',
  },
  {
    name: 'filter-slash',
    className: 'pi pi-filter-slash',
  },
  {
    name: 'flag',
    className: 'pi pi-flag',
  },
  {
    name: 'flag-fill',
    className: 'pi pi-flag-fill',
  },
  {
    name: 'folder',
    className: 'pi pi-folder',
  },
  {
    name: 'folder-open',
    className: 'pi pi-folder-open',
  },
  {
    name: 'folder-plus',
    className: 'pi pi-folder-plus',
  },
  {
    name: 'forward',
    className: 'pi pi-forward',
  },
  {
    name: 'gauge',
    className: 'pi pi-gauge',
  },
  {
    name: 'gift',
    className: 'pi pi-gift',
  },
  {
    name: 'github',
    className: 'pi pi-github',
  },
  {
    name: 'globe',
    className: 'pi pi-globe',
  },
  {
    name: 'google',
    className: 'pi pi-google',
  },
  {
    name: 'graduation-cap',
    className: 'pi pi-graduation-cap',
  },
  {
    name: 'hammer',
    className: 'pi pi-hammer',
  },
  {
    name: 'hashtag',
    className: 'pi pi-hashtag',
  },
  {
    name: 'headphones',
    className: 'pi pi-headphones',
  },
  {
    name: 'heart',
    className: 'pi pi-heart',
  },
  {
    name: 'heart-fill',
    className: 'pi pi-heart-fill',
  },
  {
    name: 'history',
    className: 'pi pi-history',
  },
  {
    name: 'home',
    className: 'pi pi-home',
  },
  {
    name: 'hourglass',
    className: 'pi pi-hourglass',
  },
  {
    name: 'id-card',
    className: 'pi pi-id-card',
  },
  {
    name: 'image',
    className: 'pi pi-image',
  },
  {
    name: 'images',
    className: 'pi pi-images',
  },
  {
    name: 'inbox',
    className: 'pi pi-inbox',
  },
  {
    name: 'indian-rupee',
    className: 'pi pi-indian-rupee',
  },
  {
    name: 'info',
    className: 'pi pi-info',
  },
  {
    name: 'info-circle',
    className: 'pi pi-info-circle',
  },
  {
    name: 'instagram',
    className: 'pi pi-instagram',
  },
  {
    name: 'key',
    className: 'pi pi-key',
  },
  {
    name: 'language',
    className: 'pi pi-language',
  },
  {
    name: 'lightbulb',
    className: 'pi pi-lightbulb',
  },
  {
    name: 'link',
    className: 'pi pi-link',
  },
  {
    name: 'linkedin',
    className: 'pi pi-linkedin',
  },
  {
    name: 'list',
    className: 'pi pi-list',
  },
  {
    name: 'list-check',
    className: 'pi pi-list-check',
  },
  {
    name: 'lock',
    className: 'pi pi-lock',
  },
  {
    name: 'lock-open',
    className: 'pi pi-lock-open',
  },
  {
    name: 'map',
    className: 'pi pi-map',
  },
  {
    name: 'map-marker',
    className: 'pi pi-map-marker',
  },
  {
    name: 'mars',
    className: 'pi pi-mars',
  },
  {
    name: 'megaphone',
    className: 'pi pi-megaphone',
  },
  {
    name: 'microchip',
    className: 'pi pi-microchip',
  },
  {
    name: 'microchip-ai',
    className: 'pi pi-microchip-ai',
  },
  {
    name: 'microphone',
    className: 'pi pi-microphone',
  },
  {
    name: 'microsoft',
    className: 'pi pi-microsoft',
  },
  {
    name: 'minus',
    className: 'pi pi-minus',
  },
  {
    name: 'minus-circle',
    className: 'pi pi-minus-circle',
  },
  {
    name: 'mobile',
    className: 'pi pi-mobile',
  },
  {
    name: 'money-bill',
    className: 'pi pi-money-bill',
  },
  {
    name: 'moon',
    className: 'pi pi-moon',
  },
  {
    name: 'objects-column',
    className: 'pi pi-objects-column',
  },
  {
    name: 'palette',
    className: 'pi pi-palette',
  },
  {
    name: 'paperclip',
    className: 'pi pi-paperclip',
  },
  {
    name: 'pause',
    className: 'pi pi-pause',
  },
  {
    name: 'pause-circle',
    className: 'pi pi-pause-circle',
  },
  {
    name: 'paypal',
    className: 'pi pi-paypal',
  },
  {
    name: 'pen-to-square',
    className: 'pi pi-pen-to-square',
  },
  {
    name: 'pencil',
    className: 'pi pi-pencil',
  },
  {
    name: 'percentage',
    className: 'pi pi-percentage',
  },
  {
    name: 'phone',
    className: 'pi pi-phone',
  },
  {
    name: 'pinterest',
    className: 'pi pi-pinterest',
  },
  {
    name: 'play',
    className: 'pi pi-play',
  },
  {
    name: 'play-circle',
    className: 'pi pi-play-circle',
  },
  {
    name: 'plus',
    className: 'pi pi-plus',
  },
  {
    name: 'plus-circle',
    className: 'pi pi-plus-circle',
  },
  {
    name: 'pound',
    className: 'pi pi-pound',
  },
  {
    name: 'power-off',
    className: 'pi pi-power-off',
  },
  {
    name: 'prime',
    className: 'pi pi-prime',
  },
  {
    name: 'print',
    className: 'pi pi-print',
  },
  {
    name: 'qrcode',
    className: 'pi pi-qrcode',
  },
  {
    name: 'question',
    className: 'pi pi-question',
  },
  {
    name: 'question-circle',
    className: 'pi pi-question-circle',
  },
  {
    name: 'receipt',
    className: 'pi pi-receipt',
  },
  {
    name: 'reddit',
    className: 'pi pi-reddit',
  },
  {
    name: 'refresh',
    className: 'pi pi-refresh',
  },
  {
    name: 'replay',
    className: 'pi pi-replay',
  },
  {
    name: 'reply',
    className: 'pi pi-reply',
  },
  {
    name: 'save',
    className: 'pi pi-save',
  },
  {
    name: 'search',
    className: 'pi pi-search',
  },
  {
    name: 'search-minus',
    className: 'pi pi-search-minus',
  },
  {
    name: 'search-plus',
    className: 'pi pi-search-plus',
  },
  {
    name: 'send',
    className: 'pi pi-send',
  },
  {
    name: 'server',
    className: 'pi pi-server',
  },
  {
    name: 'share-alt',
    className: 'pi pi-share-alt',
  },
  {
    name: 'shield',
    className: 'pi pi-shield',
  },
  {
    name: 'shop',
    className: 'pi pi-shop',
  },
  {
    name: 'shopping-bag',
    className: 'pi pi-shopping-bag',
  },
  {
    name: 'shopping-cart',
    className: 'pi pi-shopping-cart',
  },
  {
    name: 'sign-in',
    className: 'pi pi-sign-in',
  },
  {
    name: 'sign-out',
    className: 'pi pi-sign-out',
  },
  {
    name: 'sitemap',
    className: 'pi pi-sitemap',
  },
  {
    name: 'slack',
    className: 'pi pi-slack',
  },
  {
    name: 'sliders-h',
    className: 'pi pi-sliders-h',
  },
  {
    name: 'sliders-v',
    className: 'pi pi-sliders-v',
  },
  {
    name: 'sort',
    className: 'pi pi-sort',
  },
  {
    name: 'sort-alpha-down',
    className: 'pi pi-sort-alpha-down',
  },
  {
    name: 'sort-alpha-down-alt',
    className: 'pi pi-sort-alpha-down-alt',
  },
  {
    name: 'sort-alpha-up',
    className: 'pi pi-sort-alpha-up',
  },
  {
    name: 'sort-alpha-up-alt',
    className: 'pi pi-sort-alpha-up-alt',
  },
  {
    name: 'sort-alt',
    className: 'pi pi-sort-alt',
  },
  {
    name: 'sort-alt-slash',
    className: 'pi pi-sort-alt-slash',
  },
  {
    name: 'sort-amount-down',
    className: 'pi pi-sort-amount-down',
  },
  {
    name: 'sort-amount-down-alt',
    className: 'pi pi-sort-amount-down-alt',
  },
  {
    name: 'sort-amount-up',
    className: 'pi pi-sort-amount-up',
  },
  {
    name: 'sort-amount-up-alt',
    className: 'pi pi-sort-amount-up-alt',
  },
  {
    name: 'sort-down',
    className: 'pi pi-sort-down',
  },
  {
    name: 'sort-down-fill',
    className: 'pi pi-sort-down-fill',
  },
  {
    name: 'sort-numeric-down',
    className: 'pi pi-sort-numeric-down',
  },
  {
    name: 'sort-numeric-down-alt',
    className: 'pi pi-sort-numeric-down-alt',
  },
  {
    name: 'sort-numeric-up',
    className: 'pi pi-sort-numeric-up',
  },
  {
    name: 'sort-numeric-up-alt',
    className: 'pi pi-sort-numeric-up-alt',
  },
  {
    name: 'sort-up',
    className: 'pi pi-sort-up',
  },
  {
    name: 'sort-up-fill',
    className: 'pi pi-sort-up-fill',
  },
  {
    name: 'sparkles',
    className: 'pi pi-sparkles',
  },
  {
    name: 'spinner',
    className: 'pi pi-spinner',
  },
  {
    name: 'spinner-dotted',
    className: 'pi pi-spinner-dotted',
  },
  {
    name: 'star',
    className: 'pi pi-star',
  },
  {
    name: 'star-fill',
    className: 'pi pi-star-fill',
  },
  {
    name: 'star-half',
    className: 'pi pi-star-half',
  },
  {
    name: 'star-half-fill',
    className: 'pi pi-star-half-fill',
  },
  {
    name: 'step-backward',
    className: 'pi pi-step-backward',
  },
  {
    name: 'step-backward-alt',
    className: 'pi pi-step-backward-alt',
  },
  {
    name: 'step-forward',
    className: 'pi pi-step-forward',
  },
  {
    name: 'step-forward-alt',
    className: 'pi pi-step-forward-alt',
  },
  {
    name: 'stop',
    className: 'pi pi-stop',
  },
  {
    name: 'stop-circle',
    className: 'pi pi-stop-circle',
  },
  {
    name: 'stopwatch',
    className: 'pi pi-stopwatch',
  },
  {
    name: 'sun',
    className: 'pi pi-sun',
  },
  {
    name: 'sync',
    className: 'pi pi-sync',
  },
  {
    name: 'table',
    className: 'pi pi-table',
  },
  {
    name: 'tablet',
    className: 'pi pi-tablet',
  },
  {
    name: 'tag',
    className: 'pi pi-tag',
  },
  {
    name: 'tags',
    className: 'pi pi-tags',
  },
  {
    name: 'telegram',
    className: 'pi pi-telegram',
  },
  {
    name: 'th-large',
    className: 'pi pi-th-large',
  },
  {
    name: 'thumbs-down',
    className: 'pi pi-thumbs-down',
  },
  {
    name: 'thumbs-down-fill',
    className: 'pi pi-thumbs-down-fill',
  },
  {
    name: 'thumbs-up',
    className: 'pi pi-thumbs-up',
  },
  {
    name: 'thumbs-up-fill',
    className: 'pi pi-thumbs-up-fill',
  },
  {
    name: 'thumbtack',
    className: 'pi pi-thumbtack',
  },
  {
    name: 'ticket',
    className: 'pi pi-ticket',
  },
  {
    name: 'tiktok',
    className: 'pi pi-tiktok',
  },
  {
    name: 'times',
    className: 'pi pi-times',
  },
  {
    name: 'times-circle',
    className: 'pi pi-times-circle',
  },
  {
    name: 'trash',
    className: 'pi pi-trash',
  },
  {
    name: 'trophy',
    className: 'pi pi-trophy',
  },
  {
    name: 'truck',
    className: 'pi pi-truck',
  },
  {
    name: 'turkish-lira',
    className: 'pi pi-turkish-lira',
  },
  {
    name: 'twitch',
    className: 'pi pi-twitch',
  },
  {
    name: 'twitter',
    className: 'pi pi-twitter',
  },
  {
    name: 'undo',
    className: 'pi pi-undo',
  },
  {
    name: 'unlock',
    className: 'pi pi-unlock',
  },
  {
    name: 'upload',
    className: 'pi pi-upload',
  },
  {
    name: 'user',
    className: 'pi pi-user',
  },
  {
    name: 'user-edit',
    className: 'pi pi-user-edit',
  },
  {
    name: 'user-minus',
    className: 'pi pi-user-minus',
  },
  {
    name: 'user-plus',
    className: 'pi pi-user-plus',
  },
  {
    name: 'users',
    className: 'pi pi-users',
  },
  {
    name: 'venus',
    className: 'pi pi-venus',
  },
  {
    name: 'verified',
    className: 'pi pi-verified',
  },
  {
    name: 'video',
    className: 'pi pi-video',
  },
  {
    name: 'vimeo',
    className: 'pi pi-vimeo',
  },
  {
    name: 'volume-down',
    className: 'pi pi-volume-down',
  },
  {
    name: 'volume-off',
    className: 'pi pi-volume-off',
  },
  {
    name: 'volume-up',
    className: 'pi pi-volume-up',
  },
  {
    name: 'wallet',
    className: 'pi pi-wallet',
  },
  {
    name: 'warehouse',
    className: 'pi pi-warehouse',
  },
  {
    name: 'wave-pulse',
    className: 'pi pi-wave-pulse',
  },
  {
    name: 'whatsapp',
    className: 'pi pi-whatsapp',
  },
  {
    name: 'wifi',
    className: 'pi pi-wifi',
  },
  {
    name: 'window-maximize',
    className: 'pi pi-window-maximize',
  },
  {
    name: 'window-minimize',
    className: 'pi pi-window-minimize',
  },
  {
    name: 'wrench',
    className: 'pi pi-wrench',
  },
  {
    name: 'youtube',
    className: 'pi pi-youtube',
  },
]

export const PRIME_ICON_COUNT = 314
