export { default as IconPicker } from './IconPicker.vue'
export { default as IconSelect } from './IconSelect.vue'
export { default as DynamicIcon } from './DynamicIcon.vue'
export { default as IconRender } from './IconRender.vue'
export * from './generated-icons'
export { useIconLoader } from './useIconLoader'
