import { readFileSync, writeFileSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const PRIMEICONS_CSS_PATH = join(
  __dirname,
  '../../../node_modules/.pnpm/primeicons@7.0.0/node_modules/primeicons/primeicons.css'
)

interface PrimeIcon {
  name: string
  className: string
}

// 从 primeicons.css 提取所有图标类名
function extractPrimeIcons(): PrimeIcon[] {
  const cssContent = readFileSync(PRIMEICONS_CSS_PATH, 'utf-8')

  // 匹配 .pi-xxx:before 或 .pi-xxx::before 类名
  const classRegex = /\.pi-([a-z0-9-]+)(?=:|::)/g
  const iconMap = new Map<string, string>()
  let match

  while ((match = classRegex.exec(cssContent)) !== null) {
    const iconName = match[1]
    const className = `pi-${iconName}`
    iconMap.set(className, iconName)
  }

  const icons: PrimeIcon[] = Array.from(iconMap.values()).map(name => ({
    name,
    className: `pi pi-${name}`,
  }))

  return icons.sort((a, b) => a.name.localeCompare(b.name))
}

// 生成图标列表
function generateIconLists() {
  console.log('Generating icon lists...')

  const primeIcons = extractPrimeIcons()
  console.log(`Found ${primeIcons.length} PrimeIcons`)

  const outputPath = join(__dirname, '../src/components/Icon/generated-icons.ts')
  const content = `// Auto-generated by scripts/generate-icon-lists.ts
// DO NOT EDIT MANUALLY

export interface PrimeIcon {
  name: string
  className: string
}

export const PRIME_ICONS: PrimeIcon[] = ${JSON.stringify(primeIcons, null, 2)}

export const PRIME_ICON_COUNT = ${primeIcons.length}
`

  writeFileSync(outputPath, content, 'utf-8')
  console.log(`Generated ${outputPath}`)
}

generateIconLists()
